### ISSUE TITLE
json.decoder error

### ISSUE THREAD

**Issue by tardar** [JackGruber/iobroker_mysql_2_influxdb#1]
Hey,
ich probiere mit deinem Script meine mySQL Daten in eine influxDB zu migrieren.
Allerdings bekomme ich einen Fehler, der beim json.decoder aufzutreten scheint.

sudo python3.7 migrate.py all
Traceback (most recent call last):
  File "migrate.py", line 17, in <module>
    db = json.loads(db)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 15 column 5 (char 303)

Ich probiere das auf einem RaspberryPi3b+ zu tun.

Hast du Tipps für mich oder kann ich dir weitere Informationen zur Verfügung stellen?

Liebe Grüße
Tardar

**Comment by JackGruber** [comment]
Deine Json ist nicht valide/richtig formatiert.

sieht die Json so aus? Hast du nur den part nach den doppelpunkten angepasst? 
```
{
  "MySQL": {
    "host": "localhost",
    "port": 3306,
    "database": "iobroker",
    "user": "xxxx",
    "password": "xxxx"
  },
  "InfluxDB": {
    "host": "localhost",
    "ssl": false,
    "port": 8086,
    "database": "iobroker",
    "retention_policy": "autogen",
    "user": "xxxx",
    "password": "xxxx",
    "store_ack_boolean": true
  }
}
```

**Comment by tardar** [comment]
Ich hab die Felder user und password bei der InfluxDB-CommandLine-Vorgabe aaskommentiert, weil der Docker Container auf meinem Knapp NAS keine Daten vorgibt.

Jetzt einkommentiert und geleert - sieht besser aus 👍 
Jetzt bekomme ich allerdings folgenden Error:

400: {"error":"unable to parse 'Fenster1_voltage ack=True,from=\"system.adapter.zigbee.0\",q=Decimal('0.0'),value=3.015 1606929249301000000': invalid boolean\nunable to parse 'Fenster1_voltage ack=True,from=\"system.adapter.zigbee.0\",q=Decimal('0.0'),value=3.015 1606923919549000000':

Zum Teil steht im Ack auch "1i" drinnen - vermutlich kommt er deswegen durcheinander, weil das kein boolscher Wert ist?


Ich nutze die Version aus dem Git Repo hier und habe die Version heute heruntergeladen.
Hast du noch eine Idee ? :)

Einen Riesen Dank :)

**Comment by JackGruber** [comment]
Hm komisch, das ist nicht die selbe fehlermeldung wie wenn das ack nicht boolean ist. 
Hast du einen phpmyadmin zugang zu deiner MySQL Datenbank? 
Wenn ja könntest du mal diese drei SQL befehler ausführen:
```
SELECT ack, count(ack) FROM ts_number GROUP BY ack;
SELECT ack, count(ack) FROM ts_bool GROUP BY ack;
SELECT ack, count(ack) FROM ts_string GROUP BY ack;
```
und das Ergebnis posten? 
Dann könnte ich evtl einen converter schreiben.
Oder du versucht es mit `"store_ack_boolean": false` das speichert das ack nicht als boolean.

**Comment by tardar** [comment]
mit dem store_ack_boolean verhält es sich leider gleich.
Das mit dem Converter klingt interessant - aber werden dann auch die Daten, wenn sie in die neue influxDb fließen korrekt abgelegt ?


Danke vielmals und beste Grüße

PS: Angehängt die Ergebnisse aus den Queries :)
<img width="990" alt="1" src="https://user-images.githubusercontent.com/40645000/100922267-f9e6c780-34dd-11eb-976d-b2a9873a36b3.png">
<img width="989" alt="2" src="https://user-images.githubusercontent.com/40645000/100922275-fc492180-34dd-11eb-876a-fbab83b6858d.png">

**Comment by JackGruber** [comment]
Hm, ok ... das sollte eigentlich schon konvertiert werden. 
Schreibt ioBroker bereits für die selben sensoren in die InfluxDB?

**Comment by tardar** [comment]
Nein, ich möchte InfluxDB nach Möglichkeit erst aktivieren, wenn die Daten drüben sind, um nicht direkt alles zu zerstören :)
Anbei nochmal einen Auszug der Fehlermeldung beim Start des Imports als txt file.

Hilft dir das ?
[migrate error.txt](https://github.com/JackGruber/iobroker_mysql_2_influxdb/files/5631655/migrate.error.txt)

**Comment by JackGruber** [comment]
Kannst du mir von deinem Sensor device_volt ein paar datensätze aus der MySQL exportieren, dann kann ich die mal bei mir reinladne und testen.

**Comment by tardar** [comment]
Würde ich gern, bin nur nicht so 100% fit für die Queries.
Habe die Daten Großteils in Grafana zur Anzeige drinnen.

Würde dir die aber natürlich exportieren, ist der datapoint2 bei mir.
Gerne auch alle Einträge, ich vermute dass sich das bei anderen Devices vom zigbee Adapter widerspiegelt.

**Comment by JackGruber** [comment]
`SELECT * FROM ts_number WHERE id IN (SELECT id FROM datapoints WHERE name='device_volt') LIMIT 0, 100`
Damit werden 100 Datensätze geladen.

**Comment by tardar** [comment]
Anbei der Export ;)
Wenn du weitere Daten brauchst - immer gerne :)
[ts_number.sql.zip](https://github.com/JackGruber/iobroker_mysql_2_influxdb/files/5631733/ts_number.sql.zip)

**Comment by JackGruber** [comment]
:/ der import lief ohne probleme.
Wie groß ist deine ganze DB? 

Evtl. ist auch das q Deld das problem. Führ mal bitte noch folgendes aus: 
```
SELECT q, count(q) FROM ts_number GROUP BY q;
SELECT q, count(q) FROM ts_bool GROUP BY q;
SELECT q, count(q) FROM ts_string GROUP BY q;
```

**Comment by tardar** [comment]
Die Daten aus ioBroker sind etwa 500MB.
In der Daten sind noch alte Daten vom fhem - aber in separaten Tabellen, die sollten ja nicht stören.

Gesamtgröße der Datenbank ist knapp 700MB

Ergebnis der Queries:
<img width="405" alt="3" src="https://user-images.githubusercontent.com/40645000/100926656-1423a400-34e4-11eb-8f8f-6a05ae5409e3.png">
<img width="465" alt="4" src="https://user-images.githubusercontent.com/40645000/100926658-14bc3a80-34e4-11eb-898b-1c5b2e04eca2.png">
<img width="544" alt="5" src="https://user-images.githubusercontent.com/40645000/100926661-14bc3a80-34e4-11eb-9d07-1e478ce05fe0.png">

**Comment by JackGruber** [comment]
Kannst du mir die Datenbank zum Download wo hochladen?

**Comment by tardar** [comment]
Klar, möchte nur ungern den Link hier öffentlich posten.
Hast du eine E-Mail Adresse für mich, wohin ich dir den Link schicken kann?

**Comment by JackGruber** [comment]
grubera@outlook.com

**Comment by tardar** [comment]
Die Mail ist raus :)
