### ISSUE TITLE
InfluxDB error

### ISSUE THREAD

**Issue by StephanTexxpro** [JackGruber/iobroker_mysql_2_influxdb#3]
Hallo,

ich versuche mich gerade an der Migration richtung influxdb, bekomme aber nur:

400: {"error":"unable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0 

1619259232713000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0

1619256769256000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0 

1619110174520000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0

1619110128636000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0

1614070361091000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0

1613049223115000000': invalid boolean\nunable to parse 'system.adapter.yahka.upload ack=False,from=\"system.adapter.sql.0\",q=Decimal('0.0'),value=0.0 

...

Hat jemand eine Idee, wie ich das in Ordnung bringen kann? Vielen Dank schon mal!
Stephan

**Comment by JackGruber** [comment]
Auf was ist `store_ack_boolean` konfiguriert in der `database.json`?

ioBroker schreibt schon Daten in die Datenbank?

**Comment by StephanTexxpro** [comment]
In der MySQL liegen rd. 7,9 GB an Daten, `store_ack_boolean `  habe ich mit true & false probiert. Die influxdb ist leer bislang,

**Comment by JackGruber** [comment]
Welche python version wird genutzt (`python -VV`) ach und welche influxDB version?

**Comment by StephanTexxpro** [comment]
Das ist 

Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]

mit

InfluxDB shell version: 1.8.5

auf einer Ubuntu 20.04-Box.

**Comment by JackGruber** [comment]
Passiert dies mit allen datenpunkten?
Wurde die Datenbank angelegt und dann ioBroker darauf konfiguriert oder nur der import gestartet?

**Comment by StephanTexxpro** [comment]
Ich habe es mal mit ` python migrate.py "hm-rega.0.%"` versucht, bricht mit dem selben Fehler ab. 

Den influxdb-Adapter habe ich jetzt mal (mit den gleichen Credentials wie in der database.json) in ioBroker gestartet, Verbindung funktioniert.

**Comment by StephanTexxpro** [comment]
Und so sieht es mit der DB aus:
`> auth
username: admin
password:
> show databases
name: databases
name
----
_internal
iobroker
`

**Comment by JackGruber** [comment]
Es solten doch die IDs von der Orginal DB dabei stehen, könnte ich von soeiner einen MySQL Dump haben?

Kannst du bitte mal dieses script probieren
https://raw.githubusercontent.com/JackGruber/iobroker_mysql_2_influxdb/test/migrate.py

**Comment by StephanTexxpro** [comment]
![2021-04-24 14_01_11-Window](https://user-images.githubusercontent.com/25078059/115958258-ff819000-a506-11eb-9bfc-43ecdd25e2f6.png)

Auch mit dem Alternativ-Skript gibt es den Fehler. Sorry!

**Comment by JackGruber** [comment]
Welche Version hat das python module `influxdb` ?

**Comment by StephanTexxpro** [comment]
Jetzt läuft es :-)

Ich habe die Module nochmal manuell geprüft, (mindestens) chardet wurde als 4.0.0 installiert, das hab ich jetzt per Hand auf 3.0.4 gezogen. Evtl. macht es Sinn, in der requirements.txt auf `chardet>=3.0.4,<4.0.0` zu egänzen?

Danke auf jeden Fall für Deinen schnellen Support!

**Comment by JackGruber** [comment]
Hm komisch, bei mir läuft es mit `chardet 4.0.0` als ich es gerade in in einer env getestet habe ...
Aber gut wenn es nun geht :)
